export interface Startup {
  id: string;
  name: string;
  description: string;
  landing_page: string;
  founders_linkedin: string[];
  submitted_at: string;
  revenue: number;
  revenue_change: number;
  status: "neutral" | "positive" | "negative";
  avatar_id: number;
  segment: string;
}

export const startups: Startup[] = [
  {
    id: "tzsooesslh",
    name: "Gradual",
    description:
      "An adaptive learning platform that breaks down complex subjects into digestible steps powered by AI. Learn what you need, when you need it.",
    landing_page: "https://trygradual.com/",
    founders_linkedin: [
      "https://www.linkedin.com/in/cuevaio/",
      "https://www.linkedin.com/in/railly-hugo/",
      "https://www.linkedin.com/in/ignacior97/",
      "https://www.linkedin.com/in/shiara-arauzo/",
      "https://www.linkedin.com/in/lizethriveros/",
      "https://www.linkedin.com/in/carlos-tarmeno/",
      "https://www.linkedin.com/in/edwardramosvillarreal/",
    ],
    submitted_at: "May 15, 2025 12:44 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 2,
    segment: "educación",
  },
  {
    id: "npfyxhnciz",
    name: "Helty",
    description:
      "Mejoramos el seguimiento post-consulta médica con AI Ayudamos a profesionales de la salud a mejorar el proceso de seguimiento postconsulta a través de un acompañamiento personalizado, garantizando la adherencia al tratamiento, la detección temprana de complicaciones y la satisfacción del paciente.",
    landing_page: "https://helty-post-consult.lovable.app/",
    founders_linkedin: [
      "https://www.linkedin.com/in/jesusdelgadodiseno/",
      "https://www.linkedin.com/in/carlabpalencia/",
    ],
    submitted_at: "May 16, 2025 08:05 am",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 2,
    segment: "salud",
  },
  {
    id: "foxi2025",
    name: "Foxi",
    description:
      "CFO agent para Startups. Proyecciones para tus estados financieros.",
    landing_page: "https://foxi-landing.lovable.app/",
    founders_linkedin: [
      "https://www.linkedin.com/in/gibran-davila?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    ],
    submitted_at: "May 18, 2025 12:47 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 1,
    segment: "finanzas",
  },
  {
    id: "ventaspro",
    name: "VentasPro AI",
    description:
      "Entrena y mejora tus habilidades de venta con nuestro sistema de simulación y evaluación potenciado por inteligencia artificial.",
    landing_page: "https://ventasproai.site/",
    founders_linkedin: [
      "https://www.linkedin.com/in/jesus-bohorquez-4026702ab/",
      "https://www.linkedin.com/in/jcpbo/",
    ],
    submitted_at: "May 19, 2025 10:09 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 4,
    segment: "ventas",
  },
  {
    id: "antiaicall",
    name: "Anti AI Call",
    description: "Your AI Secretary that answers all your undesired calls",
    landing_page: "https://antiaicall.com/",
    founders_linkedin: [
      "https://www.linkedin.com/in/sebastian-arango-vergara/",
    ],
    submitted_at: "May 20, 2025 01:42 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 1,
    segment: "IA",
  },
  {
    id: "copilot2025",
    name: "Copilot RE",
    description:
      "8 agentes de IA que todo realtor necesita para liberarse del 60% del tiempo de tareas repetitivas y manuales para dedicarse a lo que realmente importa. Construir confianza con sus prospectos y cerrar ventas.",
    landing_page: "https://copilot-re.com",
    founders_linkedin: ["https://linkedin.com/in/oriel-esquivel-5aa5071"],
    submitted_at: "May 19, 2025 12:58 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 1,
    segment: "inmobiliario",
  },
  {
    id: "bymeet2025",
    name: "ByMeet AI",
    description:
      "ByMeet.ai es una plataforma para grabar conferencias, transcribir contenido y generar resúmenes inteligentes con IA. Compatible con múltiples plataformas, ofrece APIs, bots automatizados y funciones personalizadas para profesionales, empresas y desarrolladores.",
    landing_page: "https://bymeet.ai/",
    founders_linkedin: [
      "https://www.linkedin.com/in/jesus-bohorquez-4026702ab/",
      "https://www.linkedin.com/in/jcpbo/",
    ],
    submitted_at: "May 19, 2025 11:57 am",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 3,
    segment: "productividad",
  },
  {
    id: "dbob2025",
    name: "dbob",
    description:
      "Escalamos las ventas de los infoproductores con procesos de venta hiper personalizado",
    landing_page: "https://dbob.tech",
    founders_linkedin: [
      "https://www.linkedin.com/in/andre-portilla?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      "https://www.linkedin.com/in/felipe-mendozap?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      "https://www.linkedin.com/in/javiermoreno1?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    ],
    submitted_at: "May 20, 2025 03:15 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 3,
    segment: "ventas",
  },
  {
    id: "aprov2025",
    name: "Aprov",
    description: "Aprobación de documentación empresarial por WhatsApp.",
    landing_page: "https://www.aprov.tech/",
    founders_linkedin: [
      "https://www.linkedin.com/in/tomas-calle/",
      "https://www.linkedin.com/in/ialmanzaj/",
    ],
    submitted_at: "May 17, 2025 01:00 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 1,
    segment: "aprobaciones",
  },
  {
    id: "onzs6ounnm",
    name: "Kinoia",
    description:
      "Hey! Somos la mejor opción de experiencias conversacionales con personalidad",
    landing_page: "https://www.kinoia.com/",
    founders_linkedin: [
      "https://www.linkedin.com/in/alejandra-rojas-garzon/",
      "https://www.linkedin.com/in/juanse-garcia/",
      "https://www.linkedin.com/in/victor-camacho-qhronus/",
    ],
    submitted_at: "May 17, 2025 01:53 am",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 1,
    segment: "conversacional",
  },
  {
    id: "morphe2025",
    name: "Morphe",
    description:
      "De la idea a agentes inteligentes de IA al instante Morphe transforma fácilmente conversaciones naturales y bocetos en agentes de inteligencia artificial poderosos, transparentes y desplegables al instante. Simplifica la integración, pruebas y despliegue—todo en una plataforma intuitiva.",
    landing_page: "http://morphe.webelopers.io/",
    founders_linkedin: [
      "https://www.linkedin.com/in/tomasbaron/",
      "https://www.linkedin.com/in/gemu/",
      "https://www.linkedin.com/in/samuel-ramirez-developer/",
    ],
    submitted_at: "May 17, 2025 02:00 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 1,
    segment: "IA",
  },
  {
    id: "ggbpcnvsjm",
    name: "dtapop.com",
    description:
      "Transforma datos en tendencia en gráficos accesibles y atractivos",
    landing_page: "http://dtapop.com/",
    founders_linkedin: ["https://www.linkedin.com/in/ricardoepretelt/"],
    submitted_at: "May 17, 2025 05:41 am",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 2,
    segment: "datos",
  },
  {
    id: "ds40igd4np",
    name: "Ezcala AI",
    description:
      "Somos un SAAS para que nuestros clientes creen agentes de IA que venden por WhatsApp.",
    landing_page: "https://ai.ezcala.co",
    founders_linkedin: [
      "https://www.linkedin.com/in/alejoroj4s?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    ],
    submitted_at: "May 16, 2025 09:09 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 4,
    segment: "IA",
  },
  {
    id: "ef1nwcssqi",
    name: "Vanguard Innovation",
    description: "Soluciones innovadoras para micro y pequeñas empresas",
    landing_page: "https://emprendoestoy.web.app/",
    founders_linkedin: ["https://www.linkedin.com/in/cristiangarciasv/"],
    submitted_at: "May 16, 2025 01:24 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 1,
    segment: "negocios",
  },

  {
    id: "sfnbsr8uwt",
    name: "SkillBloom",
    description:
      "Plataforma AI-first enfocada para personas que busquen emprender, cambiar de carrera o aprender habilidades en demanda mediante una profunda evaluación de habilidades únicas con IA, planeación de un roadmap personalizado, seguimiento y coaching IA, mentoría profesional y emparejamiento con posibles co-founders con habilidades complementarias",
    landing_page: "https://skillbloom-beta.vercel.app/",
    founders_linkedin: [
      "https://www.linkedin.com/in/diego-alejandro-molano-roa-1444681b6/",
      "https://www.linkedin.com/in/juan-vargas-3b4a12295/",
      "https://www.linkedin.com/in/lfmolano/",
    ],
    submitted_at: "May 15, 2025 10:37 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 1,
    segment: "rrhh",
  },
  {
    id: "gcs0xhww7d",
    name: "Tresqu",
    description:
      "Agente de inteligencia artificial que te ayuda con tus finanzas",
    landing_page: "https://tresqu.com/",
    founders_linkedin: [
      "https://www.linkedin.com/in/jaimeaza/",
      "https://www.linkedin.com/in/edison-alexander-escobar-isac-as-907642219/",
    ],
    submitted_at: "May 15, 2025 12:38 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 3,
    segment: "finanzas",
  },
  {
    id: "mxrvfws86q",
    name: "Chatty",
    description: "Sistema de gestión administrativa potenciando por IA",
    landing_page: "https://github.com/nicobytes/open-stylo",
    founders_linkedin: [
      "https://www.linkedin.com/in/vpzulema/",
      "https://www.linkedin.com/in/nicobytes/",
    ],
    submitted_at: "May 21, 2025 08:46 am",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 3,
    segment: "productividad",
  },
  {
    id: "v1jzknwgky",
    name: "Mentaclass",
    description:
      "- Menta es un emprendimiento que busca ayudar a estudiantes de secundaria, media, y universidad, a alcanzar sus metas académicas y universitarias - por medio de una plataforma gamificada donde estudiantes contestan preguntas que se traducen a una matriz de conocimientos -conformada de contenido para guiar y motivar el aprendizaje en las áreas evaluadas. Los contenidos y las preguntas van a ser powered by un buscador de IA específico a páginas web educativas, de tal manera de que las necesidades de cada estudiante sean cubiertas.",
    landing_page: "https://mentaclass.com",
    founders_linkedin: [
      "https://github.com/issaza278",
      "https://github.com/martijaram",
    ],
    submitted_at: "May 17, 2025 12:32 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 3,
    segment: "educación",
  },
  {
    id: "d8fszcmxqs",
    name: "Tu profe de ia",
    description:
      "Tu ProfeDeIA es una startup especializada en el desarrollo de soluciones con inteligencia artificial, enfocada en la creación de agentes conversacionales, automatización de procesos y herramientas inteligentes personalizadas. Combinamos tecnología de vanguardia con un enfoque práctico para potenciar la productividad y competitividad de emprendedores y pequeñas empresas.",
    landing_page: "https://tuprofedeia.com.co/landing",
    founders_linkedin: [
      "https://www.linkedin.com/in/john-alexander-paez-arias-543b0254",
    ],
    submitted_at: "May 14, 2025 09:57 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 2,
    segment: "educación",
  },
  {
    id: "mspuwrv21h",
    name: "Zero Waste",
    description:
      "Zero Waste es tu compañera inteligente: propone menús semanales a tu medida, te enseña a aprovechar cada ingrediente y te ayuda a sacar el máximo provecho de los sobrantes.",
    landing_page: "https://zerowaste.lat/",
    founders_linkedin: [
      "https://www.linkedin.com/in/wolfcito/",
      "https://www.linkedin.com/in/kely-aristizabal/",
    ],
    submitted_at: "May 14, 2025 09:06 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 4,
    segment: "foodtech",
  },
  {
    id: "mhju06t5gi",
    name: "AprendeMate",
    description:
      "Plataforma para enseñar Matemáticas con IA, analítica de aprendizaje personalizado y multimodalidad.",
    landing_page: "https://previewmvp.wixsite.com/aprendemate",
    founders_linkedin: [
      "https://www.linkedin.com/in/edith-romero-a03a74150?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    ],
    submitted_at: "May 14, 2025 08:35 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 3,
    segment: "educación",
  },
  {
    id: "yayiv4tig9",
    name: "irrelevant club",
    description: "AI assistant para VC - Investment memo, y due diligence",
    landing_page: "https://stayirrelevant.com",
    founders_linkedin: [
      "https://www.linkedin.com/in/juan-pablo-gomez-730145212?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    ],
    submitted_at: "May 15, 2025 10:15 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 4,
    segment: "finanzas",
  },
  {
    id: "pvhajjbwoh",
    name: "Irradialab",
    description:
      ": IrradIA Lab es un laboratorio de inteligencia artificial emergente (startup) enfocado en guiar y capacitar a empresas para adoptar estratégicamente tecnologías de IA generativa. Funcionamos como un socio tecnológico, transformando datos y procesos complejos en soluciones de IA personalizadas y eficientes que generan valor de negocio tangible.",
    landing_page: "https://irradialab.com/",
    founders_linkedin: [
      "https://www.linkedin.com/in/sntggmz/",
      "https://www.linkedin.com/in/ximena-estefania-ria%C3%B1o-agudelo-5b39b75a/",
      "https://www.linkedin.com/in/hdinsuastic/",
    ],
    submitted_at: "May 15, 2025 10:06 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 3,
    segment: "IA",
  },
  {
    id: "k4pital2025",
    name: "K4pital",
    description:
      "Herramienta para que tomes el control de tus finanzas personales.",
    landing_page: "https://k4pital.com/",
    founders_linkedin: [
      "https://www.linkedin.com/in/andres-urbano-alban/",
      "https://www.linkedin.com/in/juan-camilo-urbano/",
    ],
    submitted_at: "May 19, 2025 11:57 am",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 4,
    segment: "finanzas",
  },
  {
    id: "yanoa2025",
    name: "YANOA",
    description:
      "App que fomenta el juego responsable y el desengancharse de problemas con el juego",
    landing_page: "https://v0-yan-oa-app.vercel.app/",
    founders_linkedin: ["https://www.linkedin.com/in/ingyamilcm"],
    submitted_at: "May 20, 2025 11:37 am",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 2,
    segment: "salud",
  },
  {
    id: "trace2025",
    name: "Trace",
    description:
      "Trace es un ERP SaaS que centraliza procesos empresariales en la nube. Utiliza blockchain propia para garantizar un registro inmutable de operaciones. Incorpora IA avanzada para automatizar y optimizar la gestión de órdenes en tiempo real.",
    landing_page: "https://trace.basecomputing.com.co",
    founders_linkedin: [
      "https://linkedin.com/in/sebastq/",
      "https://www.linkedin.com/in/andr%C3%A9s-juli%C3%A1n-m%C3%BAnera-uribe-912664316/",
      "https://www.linkedin.com/in/santiago-urrego-ramirez-b07100211/",
    ],
    submitted_at: "May 19, 2025 11:05 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 3,
    segment: "negocios",
  },
  {
    id: "inzigne2025",
    name: "Inzigne",
    description: "Aprendizaje efectivo incluyendo blockchain, AI e incentivos",
    landing_page: "https://hackaton-fusion-avalanche.vercel.app/",
    founders_linkedin: [
      "https://www.linkedin.com/in/mario-enrique-cuberos-hern%C3%A1ndez-27b111149?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    ],
    submitted_at: "May 19, 2025 04:31 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 2,
    segment: "educación",
  },
  {
    id: "integralaia",
    name: "IntegraLaIA",
    description:
      "Agentes de IA multicanal con un Hub MCP que simplifica la integración con herramientas y APIs en Colombia.",
    landing_page: "https://integralaia.com",
    founders_linkedin: ["https://www.linkedin.com/in/brayan-villalobos/"],
    submitted_at: "May 19, 2025 04:16 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 3,
    segment: "IA",
  },
  {
    id: "mind2in2025",
    name: "Mind2.in",
    description:
      "Mind2.in is a no-code AI platform that helps professionals transform their knowledge into smart digital clones. These clones talk, respond, and support clients 24/7 — just like their creator — and can be shared, embedded, or monetized via subscriptions. Professionals upload content (Q&A, docs, or voice), personalize the tone and function of the AI, and instantly deploy their own assistant. Mind2.in automates repetitive answers, multiplies reach, and creates passive income streams.",
    landing_page: "https://mind2.in/",
    founders_linkedin: ["https://www.linkedin.com/in/marylinalarcon/"],
    submitted_at: "May 19, 2025 12:47 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 2,
    segment: "IA",
  },
  {
    id: "whatever2025",
    name: "Whatever AI",
    description:
      "Todo el ecosistema de soluciones IA para impulsar, automatizar y transformar tu negocio en un solo lugar.",
    landing_page: "https://whateverai.dev/",
    founders_linkedin: ["https://www.linkedin.com/in/marylinalarcon/"],
    submitted_at: "May 19, 2025 12:44 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 4,
    segment: "IA",
  },
  {
    id: "parallelo25",
    name: "Parallelo AI",
    description:
      "Plataforma de orquestación, creación y despliegue de Agentes de AI. Transformamos el conocimiento de la empresa en Agentes de AI que automatizan tareas y dan soporte especializado a cada departamento.",
    landing_page: "https://www.parallelo.ai/",
    founders_linkedin: [
      "https://www.linkedin.com/in/pablogavirial/",
      "https://www.linkedin.com/in/sofrito/",
    ],
    submitted_at: "May 19, 2025 12:42 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 3,
    segment: "IA",
  },
  {
    id: "softkad2025",
    name: "Softkad",
    description:
      "Startup que desarrolla un sistema de facturación POS inteligente diseñado para MIPYMES, comercios e industrias. Nuestra solución automatiza procesos operativos, centraliza la información contable y fiscal, y facilita el cumplimiento normativo. Operamos bajo un modelo de negocio B2B por suscripción, con planes escalables en la nube, ofreciendo eficiencia, sostenibilidad y transformación digital accesible para pequeñas y medianas empresas.",
    landing_page: "https://softkad.com/",
    founders_linkedin: ["https://www.linkedin.com/in/desarrollo-oalvarez/"],
    submitted_at: "May 19, 2025 12:27 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 1,
    segment: "finanzas",
  },
  {
    id: "reglasjuego",
    name: "Las Reglas de Juego",
    description:
      "La App de Las Reglas de Juego te permite conocer, de forma rápida y sencilla, los datos más importantes de tu empresa.",
    landing_page: "https://las-reglas-de-juego-mhoy.glide.page/dl/6471c6",
    founders_linkedin: [
      "https://www.linkedin.com/in/carlosandreshernandezochoa",
    ],
    submitted_at: "May 19, 2025 12:11 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 2,
    segment: "negocios",
  },
  {
    id: "pg2wccbmhn",
    name: "Agente live",
    description:
      "Es un asistente virtual educativo con voz y avatar animado que responde dudas en español dentro de cualquier lugar. Usa inteligencia artificial para generar respuestas claras y naturales, que son convertidas en voz con sincronización labial, creando una experiencia más humana y cercana para las personas.",
    landing_page: "https://agentesias.com/",
    founders_linkedin: [
      "www.linkedin.com/in/jhon-henry-matoma-trujillo-b87070280",
    ],
    submitted_at: "May 21, 2025 09:35 am",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 2,
    segment: "educación",
  },
  {
    id: "qtdzgxl7z5",
    name: "SV Finder",
    description:
      "SV Finder quiere brindarte un solo lugar para que encuentres el servicio que necesitas ya sea para tu hogar o evento",
    landing_page: "svfinder.lovable.app",
    founders_linkedin: ["https://www.linkedin.com/in/valentina-seveso-nuesch/"],
    submitted_at: "May 20, 2025 11:26 pm",
    revenue: 0,
    revenue_change: 0,
    status: "neutral",
    avatar_id: 4,
    segment: "servicios",
  },
];
